### ISSUE TITLE
hdRPR doesnt render at all( not even an empty scene/stage)

### ISSUE THREAD

**Issue by framkant** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#156]
HW: MacBookPro 2017 with 560mm 16GB RAM and i7
SW: Mojave, 10.14.6. H18.0.287, hdRPR 1.0.0

RPR is installed and visible in the stage view renderer menu. When selected I get no rendering and an error message (warning triangle) stating: "Render delegate hdRprPlugin failed to render".

I first tried with a rubber toy scene with a light and when that failed I tried with a standard cube but that also failed.

After this error, RPR is no longer visible as a choice in the stage view menu.
No need for repro file since this fails with an empty scene.

**Comment by hshakula** [comment]
Hi, I have never seen such an error before, let's investigate it.
Please set environment variable TF_DEBUG to
"TF_DLOPEN TF_PRINT_ALL_POSTED_ERRORS_TO_STDERR" and try again. Should be much more output in the console

**Comment by framkant** [comment]
ok, got this:
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_Plugins.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_Plugins.dylib' (handle=0x7f9ec79d9d60)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_usd.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_usd.dylib' (handle=0x11b91d128)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_NC.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_NC.dylib' (handle=0x7f9eaa0f3340)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_sdf.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_sdf.dylib' (handle=0x11b91d428)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_Plugins.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_Plugins.dylib' (handle=0x7f9ec79d9d60)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdStorm.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdStorm.dylib' (handle=0x7f9eaa0fbd00)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_glf.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_glf.dylib' (handle=0x11b91eb50)
Runtime Error: in GlfPostPendingGLErrors at line 85 of /Users/prisms/builder-new/WeeklyDevToolsHEAD/dev_tools/src/usd/usd-19.11/USD-py2.7/pxr/imaging/lib/glf/diagnostic.cpp -- GL error: invalid enumerant, reported from virtual pxrInternal_v0_19__pxrReserved__::HdxColorCorrectionTask::~HdxColorCorrectionTask()
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_usdImaging.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_usdImaging.dylib' (handle=0x11b91f9a8)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib' (handle=0x0)
TfDlopen: [error on opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib': dlopen(/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib, 2): Library not loaded: @rpath/libRadeonImageFilters64.dylib
  Referenced from: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib
  Reason: no suitable image found.  Did find:
	/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/./libRadeonImageFilters64.dylib: file too short
	/Applications/Houdini/Houdini18.0.287/Houdini Indie 18.0.287.app/Contents/MacOS/../../../Frameworks/Houdini.framework/Versions/18.0/Libraries/libRadeonImageFilters64.dylib: file too short
Coding Error: in _Load at line 248 of /Users/prisms/builder-new/WeeklyDevToolsHEAD/dev_tools/src/usd/usd-19.11/USD-py2.7/pxr/base/lib/plug/plugin.cpp -- Load of '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib' for 'hdRpr' failed: dlopen(/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib, 2): Library not loaded: @rpath/libRadeonImageFilters64.dylib
  Referenced from: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib
  Reason: no suitable image found.  Did find:
	/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/./libRadeonImageFilters64.dylib: file too short
	/Applications/Houdini/Houdini18.0.287/Houdini Indie 18.0.287.app/Contents/MacOS/../../../Frameworks/Houdini.framework/Versions/18.0/Libraries/libRadeonImageFilters64.dylib: file too short

**Comment by bsavery** [comment]
I updated the build in https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/releases/tag/v1.0.0

It looks like the RIF library wasnt copied but the symlink to it was.  Should be fixed now.

**Comment by framkant** [comment]
downloaded and tested again but it still fails. out:
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_Plugins.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_Plugins.dylib' (handle=0x7f9db81d0da0)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_usd.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_usd.dylib' (handle=0x10911d128)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_NC.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_NC.dylib' (handle=0x7f9db87ca3e0)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_sdf.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_sdf.dylib' (handle=0x10911d428)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_Plugins.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_Plugins.dylib' (handle=0x7f9db81d0da0)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdStorm.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdStorm.dylib' (handle=0x7f9db87cb640)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_glf.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_glf.dylib' (handle=0x10911eb50)
Runtime Error: in GlfPostPendingGLErrors at line 85 of /Users/prisms/builder-new/WeeklyDevToolsHEAD/dev_tools/src/usd/usd-19.11/USD-py2.7/pxr/imaging/lib/glf/diagnostic.cpp -- GL error: invalid enumerant, reported from virtual pxrInternal_v0_19__pxrReserved__::HdxColorCorrectionTask::~HdxColorCorrectionTask()
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_usdImaging.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_usdImaging.dylib' (handle=0x10911f9a8)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib' (handle=0x0)
TfDlopen: [error on opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib': dlopen(/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib, 2): Library not loaded: @rpath/libRadeonImageFilters64.dylib
  Referenced from: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib
  Reason: no suitable image found.  Did find:
	/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/./libRadeonImageFilters64.dylib: file too short
	/Applications/Houdini/Houdini18.0.287/Houdini Indie 18.0.287.app/Contents/MacOS/../../../Frameworks/Houdini.framework/Versions/18.0/Libraries/libRadeonImageFilters64.dylib: file too short
Coding Error: in _Load at line 248 of /Users/prisms/builder-new/WeeklyDevToolsHEAD/dev_tools/src/usd/usd-19.11/USD-py2.7/pxr/base/lib/plug/plugin.cpp -- Load of '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib' for 'hdRpr' failed: dlopen(/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib, 2): Library not loaded: @rpath/libRadeonImageFilters64.dylib
  Referenced from: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib
  Reason: no suitable image found.  Did find:
	/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/./libRadeonImageFilters64.dylib: file too short
	/Applications/Houdini/Houdini18.0.287/Houdini Indie 18.0.287.app/Contents/MacOS/../../../Frameworks/Houdini.framework/Versions/18.0/Libraries/libRadeonImageFilters64.dylib: file too short

**Comment by hshakula** [comment]
Absolutely the same error. Make sure `/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libRadeonImageFilters64.dylib` is not symlink anymore. What is the output of ```ls -la /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libRadeonImageFilters64.dylib```?

**Comment by bsavery** [comment]
To add more detail you might need to remove the old one  ```rm /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libRadeonImageFilters64.dylib``` and then install the new package

**Comment by framkant** [comment]
I have removed the .dylib as per above and reinstalled. The install.command does not work anynore so I have to do it using python install.py instead. However, RPR still doesn't render. Checking `ls -la /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libRadeonImageFilters64.dylib` results in `ls: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libRadeonImageFilters64.dylib: No such file or directory` . This is my install log: `hdRpr will be installed to "/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current"
Do you agree? [y/n]
y
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/._hdRpr-Houdini-1.0.0-Darwin
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/.DS_Store
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/._.DS_Store
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/._Resources
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/._Libraries
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Resources/._houdini
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/.DS_Store
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/._.DS_Store
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/libTahoe64.dylib
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/._libTahoe64.dylib
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/libRadeonImageFilters64.dylib
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/._usd_plugins
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/libRadeonProRender64.dylib
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/._libRadeonProRender64.dylib
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Resources/houdini/._soho
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/._hdRpr
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr.dylib
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/._hdRpr.dylib
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Resources/houdini/soho/._parameters
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/._resources
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Resources/houdini/soho/parameters/HdRprPlugin_Viewport.ds
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Resources/houdini/soho/parameters/._HdRprPlugin_Viewport.ds
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/plugInfo.json
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/._plugInfo.json
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/._images
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/._rif_models
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/images/restartRequired.png
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/images/._restartRequired.png
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/._kernels
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/esrgan-03x2x32-273866.pb
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/._esrgan-03x2x32-273866.pb
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/denoise_c3_ldr.pb
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/._denoise_c3_ldr.pb
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/rif_models.version
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/._rif_models.version
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/denoise_c9_ldr.pb
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/._denoise_c9_ldr.pb
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/denoise_c3_hdr.pb
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/._denoise_c3_hdr.pb
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/upscale2x_fast.pb
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/._upscale2x_fast.pb
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/denoise_c9_hdr.pb
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/._denoise_c9_hdr.pb
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/esrgan-05x3x32-278391.pb
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/._esrgan-05x3x32-278391.pb
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/gfx803_36.cd.pdb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/._gfx803_36.cd.pdb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/gfx902_8.cd.updb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/._gfx902_8.cd.updb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/gfx900_56.cd.pdb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/._gfx900_56.cd.pdb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/gfx900_64.cd.pdb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/._gfx900_64.cd.pdb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/gfx906_60.cd.updb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/._gfx906_60.cd.updb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/gfx906_60.cd.pdb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/._gfx906_60.cd.pdb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/gfx803_64.cd.pdb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/._gfx803_64.cd.pdb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/gfx906_56.cd.pdb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/._gfx906_56.cd.pdb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/gfx906_64.cd.pdb.txt
-- Installing: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/Current/__MACOSX/hdRpr-Houdini-1.0.0-Darwin/Libraries/usd_plugins/hdRpr/resources/rif_models/kernels/._gfx906_64.cd.pdb.txt
Successfully installed` and this is the output from H terminal when not rendering: `TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_Plugins.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_Plugins.dylib' (handle=0x7fea82e032f0)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_usd.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_usd.dylib' (handle=0x10cec3128)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_NC.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_NC.dylib' (handle=0x7fea68c40eb0)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_sdf.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_sdf.dylib' (handle=0x10cec3428)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_Plugins.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Resources/houdini/dso/usd/USD_Plugins.dylib' (handle=0x7fea82e032f0)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdStorm.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdStorm.dylib' (handle=0x7fea68c4b350)
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_glf.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/libpxr_glf.dylib' (handle=0x10cec4b50)
Runtime Error: in GlfPostPendingGLErrors at line 85 of /Users/prisms/builder-new/WeeklyDevToolsHEAD/dev_tools/src/usd/usd-19.11/USD-py2.7/pxr/imaging/lib/glf/diagnostic.cpp -- GL error: invalid enumerant, reported from virtual pxrInternal_v0_19__pxrReserved__::HdxColorCorrectionTask::~HdxColorCorrectionTask()
TfDlopen: [opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib' (flag=2)...
TfDlopen: [opened] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib' (handle=0x0)
TfDlopen: [error on opening] '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib': dlopen(/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib, 2): Library not loaded: @rpath/libRadeonImageFilters64.dylib
  Referenced from: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib
  Reason: image not found
Coding Error: in _Load at line 248 of /Users/prisms/builder-new/WeeklyDevToolsHEAD/dev_tools/src/usd/usd-19.11/USD-py2.7/pxr/base/lib/plug/plugin.cpp -- Load of '/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib' for 'hdRpr' failed: dlopen(/Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib, 2): Library not loaded: @rpath/libRadeonImageFilters64.dylib
  Referenced from: /Applications/Houdini/Houdini18.0.287/Frameworks/Houdini.framework/Versions/18.0/Libraries/usd_plugins/hdRpr.dylib
  Reason: image not found
`

**Comment by hshakula** [comment]
Currently, macOS package is kinda broken, it's gonna be fixed on release page soon, for now, you can download fixed package [here](https://drive.google.com/open?id=1gl3reFDzjSbfWsO6bjHWCtQGL3v08TnP)

**Comment by hshakula** [comment]
The release build for macOS was updated. So I can say that this issue is resolved. @framkant, could you confirm?

**Comment by framkant** [comment]
Yes, your fixes made it run.
